apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  namespace: psql
spec:
  selector:
    matchLabels:
        app: go
  replicas: 1
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
        - name: go-image
          image:  cybraryamin/vault:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
