apiVersion: v1
data:
  default.conf: |-
    server {
    listen 80 default_server;
    root /usr/share/nginx/html/;
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log main;    
    include /etc/nginx/default.d/*.conf;
    location / {
       auth_basic                  "Restricted";
       auth_basic_user_file        /mnt/.htpasswd;
      }
    error_page 401 /denied;
    location = /denied {
        return 403;
      }

    error_page 404 /404.html;
    location = /404.html {
      }

     error_page 500 502 503 504 /50x.html;
     location = /50x.html {
       }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: "{{ .Release.Name }}-configmap"
  namespace: {{ .Release.Namespace }}
 
