apiVersion: v1
kind: Service
metadata:
  labels:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: {{ .Values.svc.port }} 
    protocol: TCP
    targetPort: {{ .Values.nginxApp.port }}
  selector:
    app: nginx
  sessionAffinity: None
  type: {{ .Values.svc.type }}
